- name: Install Java
  yum:
    name: "{{redhat_java_package_name}}"
    state: latest
  when: install_java
- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
